### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-variant#13]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] product_variant_available_in_pos
- [ ] product_variant_cost_price
- [ ] product_variant_csv_import
- [x] ~~product_variant_multi_advanced~~ - Removed as obsolete
- [x] ~~product_variant_multi~~ - Removed as obsolete
- [x] product_variant_supplierinfo - By @guewen - #35 
- [ ] product_variant_sale_price
- [ ] product_variant_weight

**Comment by joeadcock** [comment]
This is a very late response, but I was curious if there was any reason product_variant_sale_delay was not in this list (or on the 9.0 branch)?  From what I can tell, it appears to be working as-is on 9.0.  Thanks!

Joe

**Comment by pedrobaeza** [comment]
This is probably because the module landed on previous branch later than the creation of this one.
