### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/product-variant#272]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_invoice_variant_configurator - By @benwillig - #326
- [x] product_variant_configurator - By @EvaSForgeFlow - #303
- [x] product_variant_default_code - By @Rferri44-S73 - #287
- [ ] product_variant_sale_price
- [ ] product_variant_configurator_manual_creation
- [x] purchase_variant_configurator - By @victoralmau - #340
- [x] purchase_variant_configurator_on_confirm - Merged into purchase_variant_configurator - By @victoralmau - #362
- [x] sale_product_variant_attribute_tax - By @carolinafernandez-tecnativa - #354
- [x] sale_variant_configurator - By @carolinafernandez-tecnativa - #353

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by esakarya** [comment]
Please add product_variant_configurator_manual_creation to migrate.

**Comment by SergioPSV** [comment]
@sbidoul Please tell me when you plan to update the product_variant_configurator module?

**Comment by sbidoul** [comment]
> @sbidoul Please tell me when you plan to update the product_variant_configurator module?
> 

I don't currently have plan to migrate this myself.

**Comment by dsolanki-initos** [comment]
Working on sale_order_line_variant_description

**Comment by ecino** [comment]
product_variant_sale_price: #290

**Comment by punt-sistemes-salva** [comment]
working on product_variant_configurator_manual_creation
