### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-variant#40]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] product_variant_available_in_pos
- [ ] product_variant_cost_price - By @dcorio - #57 
- [ ] product_variant_csv_import
- [x] ~~product_variant_multi~~ - Removed as obsolete
- [x] ~~product_variant_multi_advanced~~ - Removed as obsolete
- [x] product_variant_configurator - By @chienandalu - #65 
- [x] product_variant_supplierinfo - By @mourad-ehm - #50 
- [ ] product_variant_sale_price - By @dcorio - #56 
- [ ] product_variant_weight
- [x] purchase_variant_configurator - By @chienandalu - #66  
- [x] purchase_variant_configurator_on_confirm - By @chienandalu - #67 
- [x] sale_variant_configurator - By @chienandalu - #70 
- [x] sale_stock_variant_configurator - By @chienandalu - #70 
- [x] stock_picking_variant_mgmt - By @pedrobaeza - #84

**Comment by blutecsolutions** [comment]
Is there any news on stock_picking_variant_mgmt for v10.0 ?
Thanks

**Comment by pedrobaeza** [comment]
The same as purchase one.

**Comment by tafaRU** [comment]
https://github.com/OCA/product-variant/tree/8.0/product_variant_uos doesn't need to be migrated from 9.0 to 10.0. See https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/base/migrations/10.0.1.3/openupgrade_general_log.txt#L208-L209 as further reference.

**Comment by tafaRU** [comment]
https://github.com/OCA/product-variant/tree/8.0/product_variant_storage_location doesn't need to be migrated as `loc_*` fields were removed since 9.0. See https://github.com/OCA/OpenUpgrade/blob/9.0/addons/stock/migrations/9.0.1.1/openupgrade_analysis_work.txt#L6-L8 as further reference.
