### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/product-variant#82]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] product_variant_available_in_pos - By @SimoRubi - #102 
- [x] product_variant_configurator - By @angelmoya - #100  
- [x] product_variant_default_code - By @Daniel-CA - #91 
- [x] product_variant_sale_price - By @SimoRubi - #103 
- [x] ~~product_variant_supplierinfo~~ - Not needed anymore - Included in core
- [ ] product_variant_template_data
- [x] purchase_order_variant_mgmt - By @javierjcf - #109
- [x] purchase_variant_configurator - By @ernestotejeda - #107
- [x] purchase_variant_configurator_on_confirm - By @ernestotejeda - #108 
- [ ] sale_order_line_variant_description
- [x] sale_order_variant_mgmt - By @pedrobaeza - #101 
- [x] sale_variant_configurator - By @angelmoya - #105 
- [x] ~~sale_stock_variant_configurator~~ Not needed anymore due to changes in core

**Comment by simoneversienti** [comment]
I'm working on migration for product_variant_configurator

**Comment by pedrobaeza** [comment]
@simoneversienti OK. It should be very straight-forward I think.

**Comment by simoneversienti** [comment]
@pedrobaeza Yes but when I create a product variant, in the variant configurator, when i click on "Value" column, i get an error ('float' object is unsubscriptable)

**Comment by pedrobaeza** [comment]
Well, you have tests for trying all the features. Have you run them to see where they fail?

**Comment by simoneversienti** [comment]
Yes, i'm trying to solve this problem

**Comment by pedrobaeza** [comment]
OK, you can make a WIP PR for sharing the current code if you prefer. Then, more people can check.

**Comment by simoneversienti** [comment]
I'm trying the module without important changes on the code but in this point I get this error. I'm checking

**Comment by Daniel-CA** [comment]
Added product_variant_default_code

**Comment by crgb001** [comment]
Any updates on v11.0 upgrade?

**Comment by crgb001** [comment]
good morning, how much will this need to complete the version? Im willing to finance all or part of it.
Anybody else interested in financing this development?
Carlos

**Comment by SimoRubi** [comment]
Migrating product_variant_available_in_pos in https://github.com/OCA/product-variant/pull/102

**Comment by SalahAdDin** [comment]
What's about product configurator in BoM lines? It makes easier fulfill the BoM materials.

**Comment by pedrobaeza** [comment]
@SalahAdDin nobody has contributed with that yet

**Comment by SalahAdDin** [comment]
@pedrobaeza I did: https://github.com/OCA/product-variant/pull/126

**Comment by pedrobaeza** [comment]
I think we can close this issue as the relevant modules have been already migrated.
